version: '3.1'
services:
    iron_server:
        build: .
        restart: always
        environment:
            IRON_USER: ironman
            IRON_PASSWORD: eiffel123
            IRON_PORT: 8080
        ports:
        - "9098:8080"
    
